apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops-blue
  name: hello-gitops-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gitops-blue-pod
  template:
    metadata:
      labels:
        app: hello-gitops-blue-pod
    spec:
      containers:
        - image: "hello-gitops:local"
          name: hello-gitops
          ports:
            - name: main
              containerPort: 8050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops-green
  name: hello-gitops-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello-gitops-green-pod
  template:
    metadata:
      labels:
        app: hello-gitops-green-pod
    spec:
      containers:
        - image: "hello-gitops:local"
          name: hello-gitops
          ports:
            - name: main
              containerPort: 8050
