apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: aramattamara/hello-gitops
  newTag: 247f0401a239f829ad67e620b445b74dd764f84a
