apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-green
images:
- name: hello-gitops
  newName: aramattamara/hello-gitops
  newTag: d61579b0600194aa1919f9daa50647fee61b094f
